#### Question 1


In [60]:
# Craeting 6x6 Numpy array with integers between 1 and 50
import numpy as np
arr = np.random.randint(1, 50, size=(6, 6))

print(arr)


[[ 7 33 34 25 28 37]
 [ 5  8 32  2 33 47]
 [45 13 11 28  4 45]
 [31 42 12 32 22 24]
 [36 14 17  7 38 28]
 [ 8 27 19 13 24 45]]


#### Question 2

In [2]:
print("first 2 row:", arr[:2])
print("\n")
print("three columns: \n", arr[:, 3:])


first 2 row: [[43 46 37 16 49 10]
 [23 10 35 10 14  8]]


three columns: 
 [[16 49 10]
 [10 14  8]
 [ 8 34 11]
 [46 36 25]
 [26 43 13]
 [23 36 28]]


In [3]:
print("even number: \n", arr[arr % 2 ==0])

even number: 
 [46 16 10 10 10 14  8  4  6 30  8 34 44 46 36 24 46 26 20 36 28]


#### Question 3


In [39]:
reshaped_arr = arr.reshape(3, 2, 6)
print("\nReshaped to (3, 2, 6):\n", reshaped_arr)


Reshaped to (3, 2, 6):
 [[[13  5 37 42 46 10]
  [48 22 30 45  7  9]]

 [[32 45 19 45 22 19]
  [41 45 18 49 12 34]]

 [[18 32 13 49  3 19]
  [40 43  7 11 14 16]]]


In [40]:
flatten_arr = reshaped_arr.flatten()
print("\nflettened back to 1D:\n:", flatten_arr)


flettened back to 1D:
: [13  5 37 42 46 10 48 22 30 45  7  9 32 45 19 45 22 19 41 45 18 49 12 34
 18 32 13 49  3 19 40 43  7 11 14 16]


#### Question 4

In [61]:
id_matrix = np.eye(4)
print("4x4 identity matrix:")
print(id_matrix)

print("\n")
diagonal_matrix = np.diag(np.arange(10, 50,10))
print(diagonal_matrix)

4x4 identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


#### Question 5

In [58]:
arr_1 = np.random.randint(1, 10, size=(3,4))
print("3x4 matrix:")
print(arr_1)

arr_2 = np.random.randint(1, 10, size=(4,3))
print("\n4x3 matrix:")
print(arr_2)

print("\n")

result = np.matmul(arr_1, arr_2)
print("Matrix Multiplication Result:")
print("result")
res = np.dot(arr_1, arr_2)
print(res)

3x4 matrix:
[[5 7 8 8]
 [8 1 4 1]
 [6 3 9 1]]

4x3 matrix:
[[6 5 2]
 [9 3 4]
 [1 3 9]
 [7 4 3]]


Matrix Multiplication Result:
result
[[157 102 134]
 [ 68  59  59]
 [ 79  70 108]]


#### Question 6

In [59]:
import numpy as np
def transform_array(arr: np.ndarray) -> np.ndarray:
    """
    Takes a 2D NumPy array and returns a new array where:
    - All even numbers are squared.
    - All odd numbers are replaced by -1.
    """
    # Copy to avoid modifying original array
    result = arr.copy()
    # Even numbers → square
    result[result % 2 == 0] = result[result % 2 == 0] ** 2
    # Odd numbers → -1
    result[result % 2 != 0] = -1
    return result
# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Original Array:")
print(arr)
print("\nTransformed Array:")
print(transform_array(arr))


Original Array:
[[1 2 3]
 [4 5 6]]

Transformed Array:
[[-1  4 -1]
 [16 -1 36]]
