Give the following matrices:
A = [2 -1 3]  B = [1  2]
    [0  4 1],     [-2 0]
                  [5 -3]
- identify the number of rows and columns in each matrix
- Determine whether the matrices can be multiplied. if so, specify whether it's (AB),(BA). or both.
- if the multiplication is defined, compute the resulting matrix

In [11]:
import numpy as np 

In [ ]:
# matrix A2x3 (2 rows, 3 columns)
# Matrix B3x2 3 rows, 2 columns


In [12]:
A = np.array([[2, -1, 3], [0, 4, 1]])     
B = np.array([[1, 2], [-2, 0],[5, -3]])

In [16]:
print(f"The dimension of matrix A is {A.shape}")
print(f"The dimension of matrix A is {B.shape}")

The dimension of matrix A is (2, 3)
The dimension of matrix A is (3, 2)


#### Matrix A can multiply Matrix B because the number of columns of A is equal to the number of rows of B 

In [ ]:
AB = np.dot(A,B)
print(f"Matrix A multiply by Matrix B \n {AB}")

Matrix A multiply by Matrix B 
 [[19 -5]
 [-3 -3]]


#### Matrix B can multiply Matrix A because the number of columns of B is equal to the number of rows of A 

In [25]:
BA = np.dot(B, A)
print(f"Matrix B multiply by Matrix A \n {BA}")

Matrix B multiply by Matrix A 
 [[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]


### Breakdown

**AB**

**First row × first column:**
(2)(1) + (-1)(-2) + (3)(5) = 2 + 2 + 15 = 19

**First row × second column:**
(2)(2) + (-1)(0) + (3)(-3) = 4 + 0 - 9 = -5

**Second row × first column:**
(0)(1) + (4)(-2) + (1)(5) = 0 - 8 + 5 = -3

**Second row × second column:**
(0)(2) + (4)(0) + (1)(-3) = 0 + 0 - 3 = -3

**Output** 
 [[19 -5]
 [-3 -3]]

**BA**

**First row × each column:**
(1)(2) + (2)(0) = 2
(1)(-1) + (2)(4) = -1 + 8 = 7
(1)(3) + (2)(1) = 3 + 2 = 5

**Second row × each column:**
(-2)(2) + (0)(0) = -4
(-2)(-1) + (0)(4) = 2
(-2)(3) + (0)(1) = -6

**Third row × each column:**
(5)(2) + (-3)(0) = 10
(5)(-1) + (-3)(4) = -5 - 12 = -17
(5)(3) + (-3)(1) = 15 - 3 = 12

**Output**
 [[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]

