In [ ]:
import numpy as np 

: 

In [ ]:
# Dataset 4 x 3 Matrix
A = np.array([[80, 70, 90],
              [60, 85, 75],
              [95, 88, 92],
              [70, 60, 65]])
# Each row represents a student and each column represents a subject
# Subjects: Math, Science, English
print("Dataset A (4x3)")
print(A)

: 

In [7]:
# Total scores per student
print("\nTotals per student")
print(A.sum(axis=1))


Totals per student
[240 220 275 195]


In [9]:
# Step 2: Average score per subject
print("\nAverages per subject")
print(A.mean(axis=0))


Averages per subject
[76.25 75.75 80.5 ]


In [14]:
# Weighted final grades
weights_A = np.array([0.5, 0.3, 0.2])
print("\nWeighted grades")
print(A @ weights_A)


Weighted grades
[79.  70.5 92.3 66. ]


In [17]:
# Compare Student3 and Student4
print("\nStudent3 - Student4")
print(A[2] - A[3])


Student3 - Student4
[25 28 27]


In [18]:
import numpy as np

In [19]:
# Dataset 5 x 4
B = np.array([[78, 82, 69, 91],
              [65, 74, 88, 70],
              [90, 85, 94, 78],
              [72, 68, 59, 80],
              [84, 90, 76, 85]])

print("\nDataset B (5x4)")
print(B)


Dataset B (5x4)
[[78 82 69 91]
 [65 74 88 70]
 [90 85 94 78]
 [72 68 59 80]
 [84 90 76 85]]


In [20]:
# Totals per student
print("\nTotals per student")
print(B.sum(axis=1))


Totals per student
[320 297 347 279 335]


In [21]:
# Average per subject
print("\nAverages per subject")
print(B.mean(axis=0))



Averages per subject
[77.8 79.8 77.2 80.8]


In [22]:
# Science is 3x more important (column index 2)
print("\nTotals with Science x3")
print((B * [1, 1, 3, 1]).sum(axis=1))


Totals with Science x3
[458 473 535 397 487]


In [23]:
# Weighted final grades (weights = [0.4, 0.2, 0.3, 0.1])
weights_B = np.array([0.4, 0.2, 0.3, 0.1])
print("\nWeighted grades")
print(B @ weights_B)


Weighted grades
[77.4 74.2 89.  68.1 82.9]


In [24]:
# Compare Student3 and Student4
print("\nStudent3 - Student4")
print(B[2] - B[3])



Student3 - Student4
[18 17 35 -2]
