In [ ]:
# !pip install torch


# Introduction to Tensors

A tensor is the core data structure used in PyTorch. It is similar to a NumPy array but provides additional features such as GPU acceleration and automatic differentiation.

Tensors generalize familiar mathematical objects:

- A scalar is a 0-dimensional tensor  
- A vector is a 1-dimensional tensor  
- A matrix is a 2-dimensional tensor  
- Higher-dimensional arrays are tensors (3D, 4D, etc.)

Deep learning models use tensors to store data such as numbers, images, audio signals, and text sequences.


# Creating Tensors in PyTorch

PyTorch provides several ways to create tensors. You can create tensors from Python lists or use built-in functions for zeros, ones, random values, and more.

Below are the main ways to create tensors:

## 1. Creating tensors from Python lists
You can pass a Python list or nested list to `torch.tensor()`. A list creates a 1D tensor, while a list of lists creates a 2D tensor.

## 2. Creating tensors using built-in functions
PyTorch includes helpful functions for generating tensors:
- `torch.zeros()` creates a tensor of zeros
- `torch.ones()` creates a tensor of ones
- `torch.rand()` creates a tensor with random numbers from a uniform distribution
- `torch.randn()` creates a tensor with random numbers from a normal distribution
- `torch.eye()` creates an identity matrix
- `torch.arange()` creates a range of evenly spaced values
- `torch.linspace()` creates evenly spaced values between two numbers


In [2]:
import torch

1. From Python lists

In [ ]:
torch.tensor(7)

tensor(7)

In [ ]:
lists = [1, 2, 3]

In [ ]:
t1 = torch.tensor(lists)

In [ ]:
t1

tensor([1, 2, 3])

In [ ]:
t2 = torch.tensor([[1,2], [3,4]])

In [ ]:
t2

tensor([[1, 2],
        [3, 4]])

#### 2. Using built-in functions

In [ ]:
a = torch.zeros(3, 3)

In [ ]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
b = torch.ones(2, 4)

In [ ]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
c = torch.rand(3, 3)

In [ ]:
c

tensor([[0.5277, 0.9671, 0.7386],
        [0.1430, 0.0331, 0.7166],
        [0.1296, 0.5872, 0.0608]])

In [ ]:
d = torch.randn(4, 4)

In [ ]:
d

tensor([[ 1.7359,  0.0969, -1.3835, -1.1284],
        [ 0.7622, -2.6038, -1.5392,  0.3527],
        [-0.6938,  1.7821, -0.6036, -1.8792],
        [-0.1695,  0.0375, -0.2697, -0.2892]])

In [ ]:
I = torch.eye(5)

In [ ]:
I

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
x = torch.arange(0, 10, step=2)

In [ ]:
x

tensor([0, 2, 4, 6, 8])

In [ ]:
l = torch.linspace(0, 1, steps=5)

In [ ]:
l

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

# Tensor Data Types (dtypes)

Each tensor has a data type that determines how its values are stored in memory. Choosing the right dtype is important for performance and precision.

Common PyTorch dtypes include:
- torch.float32
- torch.float64
- torch.int32
- torch.int64
- torch.bool

You can:
- Specify dtype when creating a tensor
- Check dtype using `.dtype`
- Convert dtype using `.to()`


In [ ]:
norm = torch.randn(3, 3)

In [ ]:
norm

tensor([[ 0.2362, -0.9935,  2.2222],
        [-1.0868, -0.7163,  0.0453],
        [ 0.3765,  1.2920,  0.6200]])

In [ ]:
norm.dtype

torch.float32

In [ ]:
t_float = torch.tensor([1.5, 2.3], dtype=torch.float32)

In [ ]:
t_float

tensor([1.5000, 2.3000])

In [ ]:
t_int = torch.tensor([1, 2, 3], dtype=torch.int64)

In [ ]:
t_int

tensor([1, 2, 3])

In [ ]:
t_int.dtype

torch.int64

In [ ]:
t_bool = torch.tensor([True, False, True], dtype=torch.bool)

In [ ]:
t_bool.dtype

torch.bool

In [ ]:
# converting a data type
t_float64 = t_float.to(torch.float64)

In [ ]:
t_float64

tensor([1.5000, 2.3000], dtype=torch.float64)

# Tensor Devices: CPU and GPU

Tensors are created on the CPU by default. PyTorch allows tensors to be moved to a GPU for faster computation during deep learning training.

Steps:
1. Check if a GPU is available.
2. Create a tensor.
3. Move the tensor to the GPU using `.to(device)`.
4. Optionally move it back to the CPU.

This is important when training neural networks, as GPUs significantly speed up computation.


In [ ]:
torch.cuda.is_available()

True

In [ ]:
if torch.cuda.is_available():
  "cuda"
else:
   "cpu"

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

 This called a "ternary operator" or a "conditional expression" in Python. It's a concise way to write an if-else statement on a single line, returning one value if the condition is true and another if it's false.

In [ ]:
x = torch.tensor([1, 2, 3])

In [ ]:
x

tensor([1, 2, 3])

In [ ]:
x_gpu = x.to(device)

In [ ]:
x_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
x_gpu.get_device()

# Converting Between NumPy Arrays and PyTorch Tensors

PyTorch integrates closely with NumPy.

- `torch.from_numpy()` converts a NumPy array to a tensor.
- `.numpy()` converts a tensor to a NumPy array.

Both objects share the same memory. Changing one will also change the other, which is efficient but should be used carefully.


In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1, 2, 3])

In [ ]:
np_array

array([1, 2, 3])

In [ ]:
np_array.dtype

dtype('int64')

In [ ]:
tensor_from_np = torch.from_numpy(np_array)

In [ ]:
tensor_from_np

tensor([1, 2, 3])

In [ ]:
tensor_from_np.dtype

torch.int64

In [ ]:
# Convert back
np_converted = tensor_from_np.numpy()

In [ ]:
np_converted

array([1, 2, 3])

In [ ]:
np_converted.dtype

dtype('int64')

# Tensor Shape and Reshaping

Every tensor has a shape that describes its dimensions.

Important operations:
- `.shape` to inspect the dimensions
- `.reshape()` to change the shape without altering data
- `.unsqueeze()` to add an extra dimension
- `.squeeze()` to remove dimensions of size 1

Reshaping is an essential concept in deep learning because neural network layers expect inputs with specific shapes.

In [ ]:
t = torch.rand(2, 3, 4)

In [ ]:
t.shape

torch.Size([2, 3, 4])

In [ ]:
x = torch.arange(12)

In [ ]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
reshaped = x.reshape(3, 4)

In [ ]:
reshaped

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
x_unsq = x.unsqueeze(0)

In [ ]:
x_unsq

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [ ]:
x_unsq.reshape(4,3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [ ]:
x_sq = x_unsq.squeeze()

In [ ]:
x_sq

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])