# Basic Arithmetic Operations with Tensors

PyTorch tensors support arithmetic operations similar to NumPy arrays. These operations are applied element-wise when tensors have the same shape.

Common arithmetic operations include:

- Addition: `a + b` or `torch.add(a, b)`
- Subtraction: `a - b`
- Multiplication: `a * b`
- Division: `a / b`
- Exponentiation: `a ** 2`
- Square root: `torch.sqrt(a)` (requires float type)

These operations allow tensors to behave like mathematical objects and are fundamental for neural network computations.


In [6]:
import torch

In [7]:
a = torch.tensor([2.0, 4.0, 6.0])

In [8]:
a

tensor([2., 4., 6.])

In [9]:
b = torch.tensor([1.0, 2.0, 3.0])

In [10]:
b

tensor([1., 2., 3.])

In [11]:
add_result = a + b

In [12]:
add_result

tensor([3., 6., 9.])

In [13]:
sub_result = a - b

In [14]:
sub_result

tensor([1., 2., 3.])

In [15]:
mul_result = a * b

In [16]:
mul_result

tensor([ 2.,  8., 18.])

In [17]:
div_result = a / b

In [18]:
div_result

tensor([2., 2., 2.])

In [19]:
exp_result = a ** 2

In [20]:
exp_result

tensor([ 4., 16., 36.])

In [21]:
sqrt_result = torch.sqrt(a)

In [22]:
sqrt_result

tensor([1.4142, 2.0000, 2.4495])

Task1: Create a (3,3) tensor and carry out the above computation. Verify your results manually too using the idea from matrices.

# Element-Wise Functions

Element-wise operations apply an operation individually to each element of a tensor.

Examples include:
- Adding two tensors of the same shape
- Multiplying element by element
- Applying mathematical functions such as `torch.sin`, `torch.cos`, `torch.exp`

These operations require tensors to have the same shape or be broadcastable.


In [23]:
x = torch.tensor([0.0, -1.0, 2.0, 45.0])

In [24]:
x

tensor([ 0., -1.,  2., 45.])

In [25]:
x*2

tensor([ 0., -2.,  4., 90.])

In [26]:
x+2

tensor([ 2.,  1.,  4., 47.])

In [27]:
x.mean()

tensor(11.5000)

In [28]:
x.sum()

tensor(46.)

In [29]:
sin_x = torch.sin(x)

In [30]:
sin_x

tensor([ 0.0000, -0.8415,  0.9093,  0.8509])

In [31]:
cos_x = torch.cos(x)

In [32]:
cos_x

tensor([ 1.0000,  0.5403, -0.4161,  0.5253])

In [33]:
exp_x = torch.exp(x)

In [34]:
exp_x

tensor([1.0000e+00, 3.6788e-01, 7.3891e+00, 3.4934e+19])

#### try `torch.pow()` and `torch.abs()`

# Matrix Operations

Matrix operations are essential in deep learning, especially for linear layers.

Common matrix operations include:

- Matrix multiplication: `torch.matmul(A, B)` or `A @ B`
- Matrix transpose: `A.t()` for 2D tensors
- Determinant: `torch.det(A)` (for square matrices)
- Inverse: `torch.inverse(A)` (if matrix is invertible)
- Dot product for vectors: `torch.dot(a, b)`

Matrix multiplication follows linear algebra rules, meaning the inner dimensions must match.


In [35]:
A = torch.randn(3, 3)

In [36]:
A

tensor([[-1.5233,  1.9083,  1.8148],
        [-0.9720,  1.1390,  0.3956],
        [-1.8058,  0.6205, -0.1477]])

In [37]:
B = torch.randn(3, 4)

In [38]:
B

tensor([[-0.3959, -0.3460, -1.4869,  1.4805],
        [-0.2150, -1.3228,  0.5256, -0.8965],
        [ 2.0607,  0.3507, -0.6298,  0.1638]])

In [39]:
matmul = torch.matmul(A, B)

In [40]:
matmul

tensor([[ 3.9325, -1.3607,  2.1248, -3.6687],
        [ 0.9552, -1.0316,  1.7948, -2.3954],
        [ 0.2773, -0.2477,  3.1041, -3.2539]])

In [41]:
# Transpose
A_T = A.t()

In [42]:
A_T

tensor([[-1.5233, -0.9720, -1.8058],
        [ 1.9083,  1.1390,  0.6205],
        [ 1.8148,  0.3956, -0.1477]])

In [43]:
detA = torch.det(A)

In [44]:
detA

tensor(1.6311)

In [45]:
torch.inverse(A) #invertible

tensor([[-0.2536,  0.8632, -0.8045],
        [-0.5260,  2.1471, -0.7121],
        [ 0.8912, -1.5332,  0.0735]])

In [46]:
v1 = torch.tensor([1.0, 2.0, 3.0])

In [47]:
v2 = torch.tensor([4.0, 5.0, 6.0])

In [48]:
dot_result = torch.dot(v1, v2)

In [49]:
dot_result

tensor(32.)

`torch.mm`

In [50]:
A = torch.tensor([[1., 2.],
                  [3., 4.]])  # Shape: (2, 2)

In [51]:

B = torch.tensor([[5., 6.],
                  [7., 8.]])  # Shape: (2, 2)

In [52]:
C = torch.mm(A, B)

In [53]:
C

tensor([[19., 22.],
        [43., 50.]])

# Indexing and Slicing Tensors

Indexing and slicing allow you to access specific elements or ranges inside a tensor.

Examples include:
- Accessing individual elements: `tensor[0]`
- Slicing a range: `tensor[0:3]`
- Accessing rows or columns in 2D tensors: `tensor[:, 0]` or `tensor[1, :]`
- Using negative indices: `tensor[-1]`

Indexing is important for data manipulation, preprocessing, and debugging during model training.


In [54]:
t = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

In [55]:
t

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

In [56]:
first_row = t[0]

In [57]:
first_row

tensor([10, 20, 30])

In [58]:
first_column = t[:, 0]

In [59]:
first_column

tensor([10, 40, 70])

In [60]:
slice_rows = t[0:2, :]

In [61]:
slice_rows

tensor([[10, 20, 30],
        [40, 50, 60]])

In [62]:
slice_cols = t[:, 1:3]

In [63]:
last_row = t[-1]

# Reshaping and Manipulating Tensors

Reshaping changes the structure of a tensor without modifying its data.

Common reshaping operations:
- `reshape()` changes the size and shape
- `view()` creates a different view of the same data (requires contiguous memory)
- `unsqueeze()` adds a dimension (useful for batch or channel dimensions)
- `squeeze()` removes dimensions of size 1
- `flatten()` converts a tensor into a 1D vector

These operations are crucial when preparing data for neural networks, which require inputs with fixed shapes.


In [64]:
x = torch.arange(12)

In [65]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
viewed = x.view(3, 4)

In [67]:
viewed

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [68]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
flattened = viewed.flatten()

In [70]:
flattened

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Task: Read about Broadcasting and check what kind of multiplication operations are supported in broadcasting